periodics:
- name: periodic-kubernetes-crio-node-throughput-perf-test-ppc64le
  tags:
  - "perfDashPrefix: crio-node-throughput"
  - "perfDashJobType: throughput"
  cluster: k8s-ppc64le-cluster
  labels:
    preset-ssh-bot: "true"
  decorate: true
  decoration_config:
    gcs_configuration:
      bucket: ppc64le-kubernetes
      path_strategy: explicit
    gcs_credentials_secret: gcs-credentials
  interval: 12h
  extra_refs:
  - base_ref: master
    org: ppc64le-cloud
    repo: kubetest2-plugins
  - base_ref: master
    org: kubernetes-sigs
    repo: kubetest2
    workdir: true
  - base_ref: master
    org: kubernetes
    repo: perf-tests
  spec:
    containers:
    - image: quay.io/powercloud/all-in-one:0.6
      resources:
        requests:
          cpu: "3000m"
        limits:
          cpu: "3000m"
      command:
      - /bin/bash
      args:
      - -c
      - |
        set -o errexit
        set -o nounset
        set -o pipefail
        set -o xtrace

        export PATH=$GOPATH/bin:$PATH
        export GO111MODULE=on

        make install-all

        pushd ../../ppc64le-cloud/kubetest2-plugins
        make install-deployer-tf
        popd

        TIMESTAMP=$(date +%s)
        K8S_BUILD_VERSION=$(curl https://storage.googleapis.com/k8s-release-dev/ci/latest.txt)
        jq --arg key0 'k8s-build-version' --arg value0 $K8S_BUILD_VERSION '. | .[$key0]=$value0' <<<'{}' > $ARTIFACTS/metadata.json

        # kubectl needed for the e2e tests
        curl -sSL https://dl.k8s.io/ci/$K8S_BUILD_VERSION/bin/linux/`go env GOARCH`/kubectl > /usr/local/bin/kubectl
        chmod +x /usr/local/bin/kubectl

        echo POD_STARTUP_LATENCY_THRESHOLD: 10s >> $GOPATH/src/github.com/kubernetes/perf-tests/clusterloader2/testing/overrides/node_containerd.yaml

        kubetest2 tf --powervs-dns k8s-tests \
          --powervs-image-name centos-9-stream-120Gb \
          --powervs-region syd --powervs-zone syd05 \
          --powervs-service-id f8640447-b356-47be-b87f-f36b72491390 \
          --powervs-ssh-key powercloud-bot-key \
          --ssh-private-key /etc/secret-volume/ssh-privatekey \
          --build-version $K8S_BUILD_VERSION \
          --runtime crio \
          --workers-count 1 \
          --cluster-name perf-test-$TIMESTAMP \
          --playbook "install-k8s-perf.yml" \
          --up --down --auto-approve --retry-on-tf-failure 3 \
          --break-kubetest-on-upfail true \
          --ignore-destroy-errors \
          --powervs-memory 16 \
          --extra-vars "kubelet_extra_args=--kube-api-qps=100 --kube-api-burst=100 --max-pods 140" --test=clusterloader2 -- \
          --test-configs=testing/node-throughput/config.yaml --test-overrides=testing/overrides/node_containerd.yaml --provider=local \
          --nodes=1 --repo-root=$GOPATH/src/github.com/kubernetes/perf-tests/

- name: periodic-kubernetes-storage-perf-test-ppc64le
  tags:
  - "perfDashPrefix: storage"
  - "perfDashJobType: storage"
  cluster: k8s-ppc64le-cluster
  labels:
    preset-ssh-bot: "true"
  decorate: true
  decoration_config:
    gcs_configuration:
      bucket: ppc64le-kubernetes
      path_strategy: explicit
    gcs_credentials_secret: gcs-credentials
  interval: 24h
  extra_refs:
  - base_ref: master
    org: ppc64le-cloud
    repo: kubetest2-plugins
  - base_ref: master
    org: kubernetes-sigs
    repo: kubetest2
    workdir: true
  - base_ref: master
    org: kubernetes
    repo: perf-tests
  spec:
    containers:
    - image: quay.io/powercloud/all-in-one:0.6
      resources:
        requests:
          cpu: "3000m"
        limits:
          cpu: "3000m"
      command:
      - /bin/bash
      args:
      - -c
      - |
        set -o errexit
        set -o nounset
        set -o pipefail
        set -o xtrace

        export PATH=$GOPATH/bin:$PATH
        export GO111MODULE=on

        make install-all

        pushd ../../ppc64le-cloud/kubetest2-plugins
        make install-deployer-tf
        popd

        TIMESTAMP=$(date +%s)
        K8S_BUILD_VERSION=$(curl https://storage.googleapis.com/k8s-release-dev/ci/latest.txt)
        jq --arg key0 'k8s-build-version' --arg value0 $K8S_BUILD_VERSION '. | .[$key0]=$value0' <<<'{}' > $ARTIFACTS/metadata.json

        # kubectl needed for the e2e tests
        curl -sSL https://dl.k8s.io/ci/$K8S_BUILD_VERSION/bin/linux/`go env GOARCH`/kubectl > /usr/local/bin/kubectl
        chmod +x /usr/local/bin/kubectl

        kubetest2 tf --powervs-dns k8s-tests \
          --powervs-image-name centos-stream-8 \
          --powervs-region syd --powervs-zone syd05 \
          --powervs-service-id c3f5354a-517e-4927-8523-890c4bf3d6c5 \
          --powervs-ssh-key powercloud-bot-key \
          --ssh-private-key /etc/secret-volume/ssh-privatekey \
          --build-version $K8S_BUILD_VERSION \
          --runtime containerd \
          --workers-count 1 \
          --cluster-name perf-test-$TIMESTAMP \
          --playbook "install-k8s-perf.yml" \
          --up --down --auto-approve --retry-on-tf-failure 3 \
          --break-kubetest-on-upfail true \
          --ignore-destroy-errors \
          --powervs-memory 16 \
          --extra-vars "kubelet_extra_args=--kube-api-qps=100 --kube-api-burst=100 --max-pods 140" --test=exec -- \
          $GOPATH/src/github.com/kubernetes/perf-tests/clusterloader2/run-e2e.sh \
          --testsuite=testing/experimental/storage/pod-startup/suite.yaml --provider=local --nodes=1 --report-dir=/logs/artifacts
